Add git authentication
TCC-Gabriel-Danillo/DevChat_Ports_And_Adapters pull request #2
Opened 2022-11-14 15:22 UTC by GabrielDVpereira

2022-11-14 23:24 UTC, DanilloGS commented on src/domain/entities/models/user.ts
> +    }
Por se tratar de uma função não seria melhor coloca-lá em um outro arquivo?

2022-11-15 00:08 UTC, DanilloGS commented on src/domain/services/authService.ts
> +    }
Esses três metodos são similares, acho que podem ser refatorados

2022-11-15 00:20 UTC, GabrielDVpereira commented on src/domain/services/authService.ts
> +    }
Hum, acho difícil pois eles possuem chamadas de apis diferentes, com retornos diferentes. Eu poderia chamar a api diretamente no código mas a legibilidade ia fica um pouco mais difícil

2022-11-15 00:22 UTC, GabrielDVpereira commented on src/domain/entities/models/user.ts
> +    }
talvez, mas por se tratar de uma função que manipula a model, achei conveniente mater-la ai.

2022-11-15 00:23 UTC, DanilloGS commented on src/infrastructure/repositories/localStorageRepository.ts
> +    if (!data) return
Esse if é necessario? Se data é undefined não há necessidade dessa verificação

2022-11-15 00:27 UTC, DanilloGS commented on src/domain/services/authService.ts
> +    async getUerInfo(token: string): Promise<GitUser | undefined> {
Typo

2022-11-15 00:28 UTC, DanilloGS requested changes
O código está bom e legivel. Acredito que seja necessario somento correções pontuais

2022-11-15 00:31 UTC, DanilloGS commented on src/domain/entities/models/user.ts
> +    }
Acho que seria válido mante-lá em um diretório `util` ou diretamento no arquivo onde está sendo usada não?

2022-11-15 00:36 UTC, GabrielDVpereira commented on src/domain/entities/models/user.ts
> +    }
Acredito que sim, vou move-la pra um helper

2022-11-15 21:07 UTC, merged